name: 'flex_components'
version: 0.0.1
description: >
  A starter template for a polymer.dart web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  browser_detect: any
  animation: any
  polymer: '0.15.5'
  paper_elements: '>=0.6.0 <0.7.0'
transformers:
- polymer:
    entry_points: 
    - web/index.html
    - web/index_layout.html
